version: '3.1'

services:
  flask:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: flask
    ports:
      - 5000:5000
    networks:
      - flaskmongo_network
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0.7
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: Str0ngUs3r
      MONGO_INITDB_ROOT_PASSWORD: Str0ngP4ssw0rd
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data:/data/db
      - ./configdb:/data/configdb
    networks:
      - flaskmongo_network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: Str0ngUs3r
      ME_CONFIG_MONGODB_ADMINPASSWORD: Str0ngP4ssw0rd
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo
    networks:
      - flaskmongo_network

networks:
  flaskmongo_network:
    driver: bridge
